### ISSUE TITLE
new  way to issue

### ISSUE THREAD

**Issue by haniali1234** [geekwise-tiffany-ranish/geekwise-academy#10]
page: home
issue: the navbar isnt in order
photo:
![screen shot 2016-04-12 at 8 56 46 am](https://cloud.githubusercontent.com/assets/11038599/14466694/ca3e2cc4-008c-11e6-8f12-2df7278f1b78.png)

**Comment by geekwise-tiffany-ranish** [comment]
@haniali1234 please review
