### ISSUE TITLE
Alignment Issue

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-tiffany-ranish/geekwise-academy#5]
page: cohort
issue: cohort drop down alignment issue

how yours looks:
![screen shot 2016-03-18 at 3 57 59 pm](https://cloud.githubusercontent.com/assets/7436666/13894200/b0068112-ed22-11e5-8a83-ec562db66bfd.png)

how it should look:
![screen shot 2016-03-18 at 3 59 31 pm](https://cloud.githubusercontent.com/assets/7436666/13894174/72b4ecf4-ed22-11e5-9008-efa4457ee72b.png)

option:
align center

**Comment by geekwise-tiffany-ranish** [comment]
@Sramos9191 please look for review
