### ISSUE TITLE
issue 1

### ISSUE THREAD

**Issue by haniali1234** [geekwise-tiffany-ranish/geekwise-academy#6]
page: about
issue: original site doesnt have any height or padding bottom 
photo:
![screen shot 2016-03-29 at 10 11 36 pm](https://cloud.githubusercontent.com/assets/11038599/14132495/651ea40e-f5fb-11e5-8ecc-7ca276d07a4b.png)

**Comment by geekwise-tiffany-ranish** [comment]
@haniali1234 fixed

**Comment by haniali1234** [comment]
page: about
issue: extra space
photo: 
![screen shot 2016-03-31 at 8 40 00 am](https://cloud.githubusercontent.com/assets/11038599/14181590/6668fac2-f71c-11e5-81bb-0bbdbc07207a.png)

**Comment by geekwise-tiffany-ranish** [comment]
@haniali1234 fixed
