### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by haniali1234** [geekwise-tiffany-ranish/geekwise-academy#8]
page: Workshops
issue: Doesnt look alike and navbar hover should be the actual word NOT the background yellow
photo: 
![screen shot 2016-03-31 at 8 52 37 am](https://cloud.githubusercontent.com/assets/11038599/14181943/08251ade-f71e-11e5-8e01-4f7ca16e0a0a.png)

**Comment by geekwise-tiffany-ranish** [comment]
fixed @haniali1234

**Comment by haniali1234** [comment]
Put some padding-left so it can be lined up with the rest of the page

**Comment by geekwise-tiffany-ranish** [comment]
@haniali1234 REVIEW plz
